os:
  - linux
  - osx
language: node_js
node_js:
  - '12'
  - '11'
  - '10'
dist: xenial
sudo: required
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
install:
  - yarn install
script:
  - yarn build
